spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_ponto_eletronico
    username: root
    password: root

security:
  basic:
    enabled: false

flyway:
  enabled: false