spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

security:
  basic:
    enabled: false

flyway:
  enabled: false

paginacao:
  qtd_por_pagina: 25