spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_ponto_eletronico
    username: root
    password: root

flyway:
  enabled: false

paginacao:
  qtd_por_pagina: 25

jwt:
  secret: _@HRL&L3tF?Z7ccj4z&L5!nU2B!Rjs3_
  expiration: 604800